# Generated by Django 3.1.3 on 2020-11-30 18:14

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VideoArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(db_index=True)),
                ('description', models.TextField(blank=True)),
                ('published_at', models.DateTimeField(db_index=True)),
                ('thumbnails', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=dict, null=True)),
                ('external_id', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
