# Generated by Django 3.1.3 on 2020-11-30 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoarchive',
            options={'ordering': ['-published_at']},
        ),
    ]
